### ISSUE TITLE
(Bug?) It's Possible to have Multiple Instances of Handheld Hardware Tools Running

### ISSUE THREAD

**Issue by nihil-us** [project-sbc/Handheld-Hardware-Tools#17]
Opening a separate issue from my previous one cos this seems like a bug, based on experience with the OG Handheld Control Panel.

It's possible to open multiple instances of HHT, unlike with HCP previously, where if you tried to run it a second time while an instance is already running in the background, an error pops up telling you about it and the second instance does not start.

The primary issue I'm facing with this is I have a 10W TDP preset on-open for HHT so I can extend the batt life of my GPD Win Mini under normal use. If a second instance of HHT opens up, it resets my gaming settings back to 10W and slows everything down to a crawl. 

Is this an intentional change for HHT? If it is, for whatever reason, could you re-implement the code that prevents the running of multiple instances as an option so that I can stop this from happening anyway?

**Comment by project-sbc** [comment]
I did add it but maybe something got broken, I’ll check it out

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: nihil-us ***@***.***>
Sent: Tuesday, July 2, 2024 1:40:29 AM
To: project-sbc/Handheld-Hardware-Tools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Handheld-Hardware-Tools] (Bug?) It's Possible to have Multiple Instances of Handheld Hardware Tools Running (Issue #17)


Opening a separate issue from my previous one cos this seems like a bug, based on experience with the OG Handheld Control Panel.

It's possible to open multiple instances of HHT, unlike with HCP previously, where if you tried to run it a second time while an instance is already running in the background, an error pops up telling you about it and the second instance does not start.

The primary issue I'm facing with this is I have a 10W TDP preset on-open for HHT so I can extend the batt life of my GPD Win Mini under normal use. If a second instance of HHT opens up, it resets my gaming settings back to 10W and slows everything down to a crawl.

Is this an intentional change for HHT? If it is, for whatever reason, could you re-implement the code that prevents the running of multiple instances as an option so that I can stop this from happening anyway?

**Comment by project-sbc** [comment]
I missed this, i added it back in the mousedev  branch and it will be in the next release!!
